# Configuração de rede e segurança
listener 1883
allow_anonymous true

# Persistência de dados (guarda as mensagens em disco caso o contentor vá abaixo)
persistence true
persistence_location /mosquitto/data/

# Logs (facilita o troubleshooting no terminal)
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout